# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "44846644e110204119d5c844d68b712d"
name = "weee-report-calculator"
application_url = "https://harry-glory-poverty-types.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testingforstoreistest.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://harry-glory-poverty-types.trycloudflare.com/auth/callback",
  "https://harry-glory-poverty-types.trycloudflare.com/auth/shopify/callback",
  "https://harry-glory-poverty-types.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
