# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "24b95980e757248e88501068a5049191"
name = "weee-calculator-app"
application_url = "https://ntsc-informal-electricity-finished.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testingforstoreistest.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ntsc-informal-electricity-finished.trycloudflare.com/auth/callback",
  "https://ntsc-informal-electricity-finished.trycloudflare.com/auth/shopify/callback",
  "https://ntsc-informal-electricity-finished.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
